"""
Builds a single seed.sql with INSERT statements for every table, ready to
paste into the Supabase SQL editor (or run via `psql -f seed.sql`).
Run AFTER 001_schema.sql has been applied.
"""
import pandas as pd
import math

OUT = "/home/claude/freight-pricing/data"
SEED_PATH = "/home/claude/freight-pricing/schema/002_seed.sql"


def sql_val(v):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "NULL"
    if isinstance(v, str):
        if v.startswith("{") and v.endswith("}"):  # postgres array literal, already formatted
            return "'" + v.replace("'", "''") + "'"
        return "'" + v.replace("'", "''") + "'"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    return str(v)


def write_inserts(f, table, df, columns=None):
    columns = columns or list(df.columns)
    f.write(f"\n-- {table} ({len(df)} rows)\n")
    f.write(f"TRUNCATE TABLE {table} RESTART IDENTITY CASCADE;\n")
    batch = []
    for _, row in df.iterrows():
        vals = ", ".join(sql_val(row[c]) for c in columns)
        batch.append(f"({vals})")
    col_list = ", ".join(columns)
    # write in chunks of 500 rows per statement for readability/performance
    for i in range(0, len(batch), 500):
        chunk = batch[i:i + 500]
        f.write(f"INSERT INTO {table} ({col_list}) VALUES\n")
        f.write(",\n".join(chunk))
        f.write(";\n")


carriers = pd.read_csv(f"{OUT}/carriers.csv")
lanes = pd.read_csv(f"{OUT}/lanes.csv")
service_levels = pd.read_csv(f"{OUT}/service_levels.csv")
carrier_rates = pd.read_csv(f"{OUT}/carrier_rates.csv")
fuel_levy_index = pd.read_csv(f"{OUT}/fuel_levy_index.csv")
accessorials = pd.read_csv(f"{OUT}/accessorials.csv")
customers = pd.read_csv(f"{OUT}/customers.csv")
customer_rate_cards = pd.read_csv(f"{OUT}/customer_rate_cards.csv")
shipments = pd.read_csv(f"{OUT}/shipments.csv")
shipments.insert(0, "shipment_id_placeholder", range(1, len(shipments) + 1))  # not written; identity col handles it
monthly_summary = pd.read_csv(f"{OUT}/monthly_account_margin_summary.csv")

with open(SEED_PATH, "w") as f:
    f.write("-- ============================================================\n")
    f.write("-- Freight Pricing & Margin Monitoring -- SEED DATA (synthetic)\n")
    f.write("-- Generated by scripts/04_build_seed_sql.py. Run after 001_schema.sql.\n")
    f.write("-- ============================================================\n")

    write_inserts(f, "carriers", carriers)
    write_inserts(f, "lanes", lanes)
    write_inserts(f, "service_levels", service_levels)
    write_inserts(f, "carrier_rates", carrier_rates,
                   columns=["carrier_id", "lane_id", "service_level_id", "weight_break_min_kg",
                            "weight_break_max_kg", "rate_per_kg", "min_charge", "effective_from", "effective_to"])
    write_inserts(f, "fuel_levy_index", fuel_levy_index)
    write_inserts(f, "accessorials", accessorials)
    write_inserts(f, "customers", customers)
    write_inserts(f, "customer_rate_cards", customer_rate_cards,
                   columns=["customer_id", "lane_id", "service_level_id", "weight_break_min_kg",
                            "weight_break_max_kg", "sell_rate_per_kg", "sell_min_charge", "markup_pct",
                            "target_margin_pct", "effective_from", "effective_to"])
    write_inserts(f, "shipments", shipments,
                   columns=["ship_date", "customer_id", "lane_id", "service_level_id", "carrier_id",
                            "actual_weight_kg", "volume_m3", "chargeable_weight_kg", "accessorials_applied",
                            "buy_cost", "sell_price", "margin_pct"])

    # KPI table needs its own schema addition (not in 001_schema.sql, written here for convenience)
    f.write("\n-- Pre-aggregated monthly margin monitoring table (built by the Python engine)\n")
    f.write("""
create table if not exists monthly_account_margin_summary (
    customer_id     text not null references customers(customer_id),
    month           date not null,
    shipment_count  integer not null,
    total_buy_cost  numeric(12,2) not null,
    total_sell_price numeric(12,2) not null,
    accessorial_shipment_count integer not null,
    target_margin_pct numeric(6,3) not null,
    realized_margin_pct numeric(6,3) not null,
    accessorial_shipment_share_pct numeric(6,2) not null,
    margin_gap_pp   numeric(6,3) not null,
    margin_flag     text not null check (margin_flag in ('ok','warning','breach')),
    low_confidence  boolean not null,
    primary key (customer_id, month)
);
""")
    write_inserts(f, "monthly_account_margin_summary", monthly_summary,
                   columns=["customer_id", "month", "shipment_count", "total_buy_cost", "total_sell_price",
                            "accessorial_shipment_count", "target_margin_pct", "realized_margin_pct",
                            "accessorial_shipment_share_pct", "margin_gap_pp", "margin_flag", "low_confidence"])

print(f"Wrote {SEED_PATH}")
import os
print(f"File size: {os.path.getsize(SEED_PATH) / 1024:.1f} KB")
